### ISSUE TITLE
Config for Single Player?

### ISSUE THREAD

**Issue by MisterShawn** [DaFuqs/HeadInTheClouds#2]
Does the current config for 1.20.1 (head_in_the_clouds-1.0.0.jar) only work for servers?

I'm creating a skyblock modpack using Head in the Clouds alongside [Raised Clouds](https://www.curseforge.com/minecraft/mc-mods/raised-clouds). I have configs for both mods set to the same y-level. Raised Clouds works correctly, but I'm still getting rain until I reach above y-level 192 or higher on single-player.

Just wondering if I'm doing something wrong, if it's a bug, or the config doesn't work for single player. Thanks for any help!

**Comment by DaFuqs** [comment]
Looks like Raised Clouds only changes the position where clouds render, without changing the cloud height exposed in `DimensionEffects`. (where minecraft saves cloud height).

This is something that should be changed in Raised Clouds, since it affects every mod that queries dimensions cloud height - creating a gap of what mods get as cloud height and what is shown to the player.
